<section>
    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
            <h1 class="page-header">
                <?php echo $this->blog->post_title; ?>
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2 blog-content">
            <?php echo $this->blog->post_content; ?>
        </div>
    </div>
</section>